// <auto-generated />
namespace WilProjectMVC2021.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class X : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(X));
        
        string IMigrationMetadata.Id
        {
            get { return "202111110326520_X"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
